// Railway runtime entrypoint.
// Keep the production email HTML exactly as generated by server-v2.js.
// Welcome emails intentionally include the direct Indomark app link;
// OTP/security emails remain link-free because their templates contain no links.
await import('./server.js');
